# permissions for end users to edit protections.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: protection-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: aws-shield-advanced-controller
    app.kubernetes.io/part-of: aws-shield-advanced-controller
    app.kubernetes.io/managed-by: kustomize
  name: protection-editor-role
rules:
- apiGroups:
  - shield.aws.geode.io
  resources:
  - protections
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - shield.aws.geode.io
  resources:
  - protections/status
  verbs:
  - get
