# permissions for end users to edit protectionpolicies.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: protectionpolicy-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: aws-shield-advanced-controller
    app.kubernetes.io/part-of: aws-shield-advanced-controller
    app.kubernetes.io/managed-by: kustomize
  name: protectionpolicy-editor-role
rules:
- apiGroups:
  - shield.aws.geode.io
  resources:
  - protectionpolicies
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - shield.aws.geode.io
  resources:
  - protectionpolicies/status
  verbs:
  - get
