---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - shield.aws.geode.io
  resources:
  - protectionpolicies
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - shield.aws.geode.io
  resources:
  - protectionpolicies/finalizers
  verbs:
  - update
- apiGroups:
  - shield.aws.geode.io
  resources:
  - protectionpolicies/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - shield.aws.geode.io
  resources:
  - protections
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - shield.aws.geode.io
  resources:
  - protections/finalizers
  verbs:
  - update
- apiGroups:
  - shield.aws.geode.io
  resources:
  - protections/status
  verbs:
  - get
  - patch
  - update
