apiVersion: shield.aws.geode.io/v1alpha1
kind: ProtectionPolicy
metadata:
  name: protectionpolicy-sample
  labels:
    app.kubernetes.io/name: aws-shield-advanced-controller
    app.kubernetes.io/managed-by: kustomize
spec:
  matchResourceTypes:
    - cloudfront/distribution
    - route53/hostedzone
    - globalaccelerator/accelerator
    - ec2/eip
    - elasticloadbalancing/loadbalancer/app
    - elasticloadbalancing/loadbalancer/classic
  matchRegions:
    - "us-west-2"
    - "us-east-1"
