apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "aws-shield-advanced-controller.fullname" . }}-controller-manager
  labels:
  {{- include "aws-shield-advanced-controller.labels" . | nindent 4 }}
  annotations:
    {{- toYaml .Values.controllerManager.serviceAccount.annotations | nindent 4 }}